#+INCLUDE: ".navigation.org"

#+INCLUDE: ../.post-header.org

#+TITLE: Composing Games from Event Graphs
#+AUTHOR: Pancake
#+DATE: 2026-07-04
#+DESCRIPTION: We analyse an architecture that composes games from event-based interactions.

Traditionally, most game architectures are built around an explicit
execution loop. Each frame executes a fixed sequence of actions. This
style of architecture prioritises functions that operate on state,
yielding a system which /proactively/ polls and acts on the world in
fixed iterations.

In this post, we construct an alternative architecture, where games
are built on networks of /reactive/ transformations. In this framing,
games are interpreted by how they react to and propagate changes. The
architectural shift will emphasise causality over sequencing, enabling
a compositional approach to game development.

** Objects to Systems: OOP and ECS as Foundations

Object-oriented approaches model games around objects, combining state
and behaviour into singular units. For example, a player may store
position, velocity, and health, and may expose methods like ~move()~,
~takeDamage()~, ~consumeItem()~. This approach classifies objects
under hierarchies, grouping similar behaviour patterns under
interfaces. Though intuitive, the system is adverse to large-scale
modifications, which require changes to deep hierarchies.

As opposed to OOP, entity component system (ECS) architectures express
data in individual components. Instead of top-down hierarchies, ECS
favours composition. A player is then only a thin wrapper on position,
velocity, and health components. Systems, where behaviour lives, only
consume components as dependencies. As game requirements change, new
systems and components are added orthogonal to existing structure,
enabling ECS systems to grow more readily than OOP systems.

Despite the modularity, the core of ECS remains a proactive
loop. Proactive loops introduce an explicit ordering of events, making
them predictable, yet some game actions only arise in response to
events. These actions, such as networking, time or progression based
triggers, and asynchronous processes, require reactions to external or
internal stimuli. Simulating reactions with active polling is highly
inefficient, leading many engines to develop event-driven layers on
top of their core loop, using systems such as event buses, delegates,
and message systems.

These systems generally achieve reactive behaviour through means that
remain external to the system, such as callbacks or shared message
buses. Through these methods, the system achieves reactive behaviour
at runtime, yet obscures the structure of interactions, meaning that
proactive architectures like ECS remain inadequate at clarifying
behaviour at the same level as data. Without a structured approach,
the exact origins of behaviour become harder to trace, hindering
debugging efforts and requiring extensive documentation of code to
express intentions.

Then, in analysing games under the alternative approach, our goal is
not to reintroduce existing reactive behaviour. Instead, our goal is
to reveal the topology of interactions that underlies reactive systems
by placing reactions to the forefront of our approach.

** Structured Reactivity

Modelling reactivity is possible in multiple ways. Our model will use
events, which act as discrete facts of the world. Events act as
anchors for reactions to attach to, allowing rigid structures to
form. More importantly, events are not solely an interpretation. In
any reactive system, a certain basis exists for all responses, and
since events only represent facts of the world, they are present in
reactive systems either implicitly or explicitly. Keeping events
implicit, as in ECS architectures, hides an induced structure between
the events and the handlers of events, directing us to an
event-centric approach to reactivity.

The event-based approach shifts focus from state and systems toward
only causality. For example, a ~KeyboardEvent~ triggers a
~PlayerMove~, or a ~TakeDamage~ triggers a ~SoundEffect~; in each
case, interactions are modelled through the consumption and emission
of events, with events representing the cause a specific behaviour
arises from. In this model, the causal chains define the patterns of
interactions.

These interactions never live in isolation: Each interaction takes
inputs from a previous interaction, all the way up to the outside
world. For instance, a keyboard input triggers a physics event, which
triggers a collision event. The full chain induces a larger structure
than a single transformation, revealing a structure of event flow.
The induced structure can be extracted as a graph, where nodes
represent events, and directed edges represent interactions.

To solidify the concept, let's look at a physics demo involving input,
physics, and object generation:

#+INCLUDE: ".game-graph-demo.html" export html

#+BEGIN_SRC dot :file games-as-graphs-full-1.svg :exports results
  digraph G {
      rankdir=LR;
      fontname="Arial";
      nodesep=0.8;

      node [shape=circle, style="rounded,filled", width=0.6, fixedsize=true, fillcolor="#e1f5fe", fontname="Arial"];
      or_game [label="or"];
      or_event [label="or"];
      choice_circle [label="or"];

      node [shape=box, fillcolor="#f7f7f7", width=default, fixedsize=false];

      subgraph cluster_physics {
          label = "Per-tick execution";
          color = lightgrey;

          GameTick -> or_game;
          or_game -> Null;
          or_game -> PhysicsTrigger;
          PhysicsTrigger -> PhysicsJob;

          Null -> PhysicsExecute;
          PhysicsJob -> PhysicsExecute;

          PhysicsExecute -> choice_circle;
          choice_circle -> PhysicsExecute;
          choice_circle -> PhysicsResult [label="Later"];
      }

      subgraph cluster_results {
          label = "Physics Resolution";
          color = lightgrey;

          Poll [label="PhysicsResult"]

          Poll -> Update;
          Update -> End_Update [style=dashed];
          End_Update [shape=point, style=invis];
      }

      subgraph cluster_input {
          label = "Input Handling";
          color = lightgrey;

          Event -> or_event;

          or_event -> FinishDraw;
          or_event -> KeepDraw;
          or_event -> StartDraw;
          or_event -> SpawnBullet;

          FinishDraw -> SpawnSurface;

          SpawnSurface -> End_Switch [style=dashed];
          KeepDraw -> End_Keep [style=dashed];
          StartDraw -> End_Start [style=dashed];
          SpawnBullet -> End_Bull [style=dashed];

          End_Switch [shape=point, style=invis];
          End_Keep [shape=point, style=invis];
          End_Start [shape=point, style=invis];
          End_Bull [shape=point, style=invis];
      }
  }
#+END_SRC

#+RESULTS:
[[file:games-as-graphs-full-1.svg]]

The graph, representing all events and interactions, is more than a
visualisation of the game: it captures the actual organisation of
reactive logic. The graph is the structure of the system, whether it
is expressed implicitly or explicitly in the implementation.

Achieving a structural representation isn't enough for our goal, we
now look to construct the graph step-by-step. Just as a proactive
framework builds games in ordered steps, a way of constructing
event-based graphs is now mandatory. Firstly, choosing a building
block is crucial, and the smallest expressive units in the graph are
events; even so, events only describe facts, and they themselves carry
no transformative power. Thus, our building blocks are the smallest
units that carry behaviour, which are individual interactions.

To bridge the gap between individual interactions and larger system
graphs, we define ways to assemble interactions. Without these
methods, the graph remains entirely descriptive rather than
constructive.

** An Algebra of Interactions

A graph can contain branching, converging, detached, and linked shapes
among others. Representing all the shapes of complex graphs with a
singular primitive composition is not possible. Instead, we develop a
set of primitive operations, each composing interactions in different
shapes.

*** Parallel composition

Some events are large, containing multiple semantic pieces. Parallel
composition allows for interactions, each handling one independent
piece of an event, to be composed into a larger interaction.

For example, both ~GameTick~ and ~Event~ originate from the outside
world, but they are treated as causally independent, even if the event
source is the same. Interactions based on ~GameTick~ can then parallel
compose with interactions based on ~Event~. This is represented with
detached pieces on the diagram.

#+BEGIN_SRC dot :file games-as-graphs-parallel.svg :exports results
  digraph G {
      rankdir=LR;
      fontname="Arial";
      nodesep=0.8;

      node [shape=circle, style="rounded,filled", width=0.6, fixedsize=true, fillcolor="#e1f5fe", fontname="Arial"];

      node [shape=box, fillcolor="#f7f7f7", width=default, fixedsize=false];
      GameTick -> Physics;
      Physics [label="..."];

      Event -> Spawns;
      Spawns [label="..."];
  }
#+END_SRC

#+RESULTS:
[[file:games-as-graphs-parallel.svg]]

*** Sequenced composition

When the output of one transformation matches the input of another,
the transformations can be chained, forming causal steps, where a long
process is broken up with intermediary events.

The example game has an asynchronous physics system, where a large
physics task is first created, then executed over time, and finally
resolved. Each step can be independently inspected, but together, they
form a long causal chain.

#+BEGIN_SRC dot :file games-as-graphs-sequence.svg :exports results
  digraph G {
      rankdir=LR;
      fontname="Arial";
      nodesep=0.8;

      node [shape=circle, style="rounded,filled", width=0.6, fixedsize=true, fillcolor="#e1f5fe", fontname="Arial"];

      node [shape=box, fillcolor="#f7f7f7", width=default, fixedsize=false];

      GameTick -> PhysicsTrigger;
      PhysicsTrigger -> PhysicsJob;

      PhysicsJob -> PhysicsExecute;

      PhysicsExecute -> PhysicsResult [label="Later"];
  }
#+END_SRC

#+RESULTS:
[[file:games-as-graphs-sequence.svg]]

*** Branching (fan-out)

A single event can feed multiple downstream interactions, allowing
divergent behaviour to develop.

To illustrate, ~Event~ can be one of many mouse events, and it can
cause one of many actions relating to ball and surface creation.

#+BEGIN_SRC dot :file games-as-graphs-fanout.svg :exports results
  digraph G {
      rankdir=LR;
      fontname="Arial";
      nodesep=0.8;

      node [shape=circle, style="rounded,filled", width=0.6, fixedsize=true, fillcolor="#e1f5fe", fontname="Arial"];
      or [label="or"];

      node [shape=box, fillcolor="#f7f7f7", width=default, fixedsize=false];
      Event -> or;
      or -> SpawnBullet;
      SpawnBullet -> End1 [style=dashed];
      or -> StartDraw;
      StartDraw -> End2 [style=dashed];
      or -> KeepDraw;
      KeepDraw -> End3 [style=dashed];
      or -> FinishDraw;
      FinishDraw -> End4 [style=dashed];

      End1 [shape=point, style=invis];
      End2 [shape=point, style=invis];
      End3 [shape=point, style=invis];
      End4 [shape=point, style=invis];
  }
#+END_SRC

#+RESULTS:
[[file:games-as-graphs-fanout.svg]]

*** Merging (fan-in)

Multiple distinct transformations may converge into a single
downstream interaction. In this case, different causal paths unify
into a shared consequence.

In the context of the game, game ticks sometimes omit the creation of
a new physics task. However, whether a task is created or not, both
paths converge to the execution of physics.

#+BEGIN_SRC dot :file games-as-graphs-fanin.svg :exports results
  digraph G {
      rankdir=LR;
      fontname="Arial";
      nodesep=0.8;

      node [shape=circle, style="rounded,filled", width=0.6, fixedsize=true, fillcolor="#e1f5fe", fontname="Arial"];

      node [shape=box, fillcolor="#f7f7f7", width=default, fixedsize=false];
      PhysicsTrigger -> Dots;
      Dots [label="..."];
      Dots -> PhysicsExecute;
      Null -> PhysicsExecute;
      PhysicsExecute -> End [style=dotted];

      End [shape=point, style=invis];

      subgraph inputs { rank=same; PhysicsTrigger; Null; }
  }
#+END_SRC

#+RESULTS:
[[file:games-as-graphs-fanin.svg]]

** Conclusion & What's Next?

So far, we've identified four operations of composition. These
operations are more than design choices. They correspond to
fundamental forms of composition studied in mathematics (for readers
familiar with category theory, our operations are similar to arrow
operations). Any graph-based representation of reactive behaviour
expresses these forms, either explicitly or implicitly.

However, we aren't done yet. So far, we ignored state, only focusing
on events. The event graph carries no structure about state, which
implies global state, at least for now. The [[file:Game-State.org][second post]] in the series
addresses the problem of state, discussing how reactive systems can
localise it.

The four operations defined here are also not sufficient in expressing
loops. In fact, the operations construct a directed acyclic graph,
expressing flat behaviour. This leaves the interactions of
~PhysicsExecute~, specifically the self-feeding loop, unrepresentible
in the current model. The [[file:Game-Loops.org][third post]] bridges the gap, also introducing
asynchronous task execution.

