#+INCLUDE: .post-header.org

#+TITLE: Games as Graphs: A Spider's Approach
#+AUTHOR: Pancake
#+DATE: 2026-07-04
#+DESCRIPTION: We formulate games as a graph, approaching from an unusual angle.

To the naked eye, a spider's web appears weak. It seems impossible for
a few strands of silk, each individually fragile, to hold up against
the real world; nevertheless, the web endures. Damage is localized,
and problems are resolved within their frame, without collapsing the
whole of the web.

Game software shares a similar tension, preferring systems that are
complex, delicate, and yet modular. A game isn't a monolith, its a
network of interactions between rendering, physics, network, inputs,
audio, and more. Each component continuously transforms others and
itself. The challenge of building a game is to craft the system so
that each piece is locally maintainable yet connected, dynamic yet
resistant.

In this post, we will explore an approach to game development inspired
by the spider. Rather than prioritizing isolated systems, our focus
will shift toward their composition, viewing the game as a graph of
interacting parts.

** Games as Data Machinery

A game can be viewed as a data flow graph. In this model, we separate
ourselves into systems and state. State can belong to the game, or it
can come from outside sources. State consists of player position, item
lists, terrain data, and others. Conversely, systems act on
state. Systems don't care about the source of the state, but only how
the data interacts. To illustrate, a physics system doesn't care about
which objects are at play, it only consumes physics states to simulate
collisions and physical forces.

Let us take a look at a physics sandbox demo to better understand this
model.

#+INCLUDE: ".game-graph-demo.html" export html

Breaking things down, we see that the game takes Inputs externally. It
holds an internal state of Balls and Surfaces. Then, the game has
interactions with Gravity, Physics, Physics Responses, and Spawners.

We will now draw a graph that separated external state, internal
state, and systems. State interacts with systems, and systems update
state. We will use directional arrows to denote state entering system,
and system updating state.

#+begin_src dot :file games-as-graphs-fsm-1.svg :exports results
  digraph G {
      rankdir=LR;
      node [shape=box, style="rounded", fontname="sans-serif"];
      edge [arrowhead=vee, minlen=2];

      Input[shape=circle];
      subgraph cluster_state {
          label = "State";
          style = dashed;
          color = black;
          
          Surfaces; Balls;
      }

      subgraph cluster_systems {
          label = "Systems";
          style = dashed;
          color = black;
  	node [shape=diamond, style="solid"]
          
          Gravity; Physics; Response; Spawner;
          
          Gravity -> Physics;
          Physics -> Response;
      }

      Balls -> Physics;
      Surfaces -> Physics;
      Response -> Balls;

      Input -> Spawner;
      Spawner -> Balls;
      Spawner -> Surfaces;
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-fsm-1.svg]]

Dataflow is an intuitive representation of procedural approaches to
games. Representing each node as its own unit of data provides a
literal representation of our graph. A Ball is an object, it enters a
Physics method simulating gravity and collision forces, and a Response
method then finalizes any remaining action before returning back.

However, generalising from concrete objects requires abstraction and
superclassing. For example, adding a separate Triangle object beside
Balls requires that we abstract a RigidBody for the Physics
system. This is fine for finished projects, but for evolving
prototypes, abstracting objects through development cycles introduces
additional mental overhead. A better approach would be to break large
objects into the smallest sensible modules outright.

To achieve the modulary, a common architecture is the use of Entity
Component Systems (ECS). In this approach, Entities (concrete data)
only carry links to their smaller Components. For example, a Ball is
formed of Position, Velocity, and CollisionBody components. This model
gives us natural Archetyping, where Components remain as pure data,
and Systems assign groups of Components their meaning. Under the
Physics system, the trio of Position, Velocity, and CollisionBody
provide a RigidBody archetype. The system no longer cares about the
larger object, instead it focuses on the units of data that it
requires, and nothing more. A Triangle is then introduced under the
same Archetype without influencing any existing instance of the
Archetype, keeping any faults in Triangle handling local.

There are also performance benefits to ECS. Instead of storing
Component data on the Entities, each Entity is instead a collection of
indices to the Component tables. Though the exact implementations
vary, an approach is to make use of the previously mentioned
archetypes to group data that is often used together into large
tables, meaning the Physics system has local, cache-friendly access to
all the data it needs.

Even if ECS is a success story on data, it loses expressive power on
interactions. Complex games may have a large range of systems like
network connections, enemy AI, complicated physics, multi-stage game
mechanics, and more. For a wide variety of systems, its often awkward
to handle everything by pure state. Having flags and queues for
asynchronous events quickly grows in complexity. Because of this, many
games using ECS create an Event Bus system that allows for easier
asynchronous processing. However, the Event Bus also obscures the true
nature of incoming and outgoing events. In the next section, we will
explore an approach that tries to alleviate this problem.

** Actions and Reactions

ECS places data at the center of its narrative. This caused problems
in asynchronous handling. Taking inspiration from the Event Bus, in
this section, we place events at the heart of our architecture,
constructing a new graph form whose edges represent the flow of
actions rather than the flow of data.

Let us revisit the game,

#+INCLUDE: ".game-graph-demo.html" export html

This time, we will place events as the nodes of our graph. Then, each
edge is a directed arrow that consumes one event as a trigger, and
emits a new event. Internally, the arrow will mutate the necessary
parts of state. There is some nuance to state handling covered on a
followup post, so for now, we will assume all state is globally
accessible to help with reasoning. The mutation will be represented as
~f(state)~ on the edge, representing that the arrow internally calls
~f~ which mutates ~state~.

#+begin_src dot :file games-as-graphs-arrow.svg :exports results
  digraph G {
  	rankdir=LR;
  	node [shape=circle, fontname="sans-serif", fixedsize=true, width=1.2];
  	edge [arrowhead=vee, minlen=2];

  	Trigger; Emission;

  	Trigger -> Emission [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>f(state)</td>
  			       </tr>
  			</table>
  		>
  	]
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-arrow.svg]]

Later on, we will analyze more of the individual properties of these
arrows. For now, lets turn our attention to the full game graph. For
the full game graph, to avoid clutter, the names of the internal ~f~
functions are hidden. We can still infer that /some/ operation happens
on the state as we pass through each edge.

#+begin_src dot :file games-as-graphs-fsm-2.svg :exports results
  digraph G {
  	rankdir=LR;
  	edge [arrowhead=vee, minlen=2];

  	X [shape=point];
  	
  	node [fontname="sans-serif", shape=rectangle, penwidth=0];
  	triggerCond[label="if tasks.empty()"];
  	triggerElse[label="else"];
  	triggerBranch[label="", width=0];

  	node [shape=circle, penwidth=1.0];
  	GameTick -> triggerBranch [arrowhead=none];
  	triggerBranch -> triggerCond [arrowhead=none]
  	triggerCond -> PhysicsTrigger;

  	triggerBranch -> triggerElse [arrowhead=none];
  	triggerElse -> X;

  	PhysicsTrigger -> PhysicsResult;

  	PhysicsResult -> X;

  	LeftClick -> X;

  	RightClick -> DrawSurf;
  	RightHold -> DrawSurf;
  	RightRelease -> DrawSurf;
  	DrawSurf -> X;
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-fsm-2.svg]]

Compared to the previous section, the new graph clarifies the system's
control flow better. For instance, the Physics section now shows a
distinct branch where the process skips physics entirely if a specific
task list is non-empty. Similarly, Input is broken down into
individual mouse events.

Remarkably, the new system is not dependent on time, update cycles, or
any specific procedure. The system is purely declarative, only
declaring the types of inputs it takes and reacts to. In contrast, an
ECS would be proactive, an ~Update()~ is called on repeat and the
various systems check for applicable data and events.

The new system is no longer code that is graph-like, the new system
/is/ the graph. The game graph /is/ also the implementation of the
game. However, this insight is only half of our troubles, we also need
a way to express the graph inside code, which is what we will explore
in the next section.

** Spider's Weave

ECS was extensible because it has a clear building block. Though our
new approach implies a compositional approach to graphs, we've yet to
formulate this. In the previous section, we had isolated a single
arrow from a trigger to an event. In this section, we will use the
individual arrow as a building block of the whole of the graph.

file:games-as-graphs-arrow.svg

From now on, ~Trigger -f> Emission~ denotes the arrow that's seen
above. We will use this text-based notation for inline explanations to
avoid breaking up the train of thought with diagrams. Now, to
construct graphs with the individual arrows, we need ways to join them
together. There isn't a single, unified operation that covers all
cases; instead, we will implement four operations, each defining a
capability, a single face, of arrows. Altogether, the four operations
will provide us the means to weave up a full web of events.

To start, our first operation considers two arrows ~a -f> b~ and
~c -g> d~. These arrows don't have any relation to one another.
Given two independent arrows like this, we can use the first operation
to lay the two arrows in parallel, so that they don't interfere.

#+begin_src dot :file games-as-graphs-arrow-parallel.svg :exports results
  digraph G {
  	rankdir=LR;
  	node [shape=circle, fontname="sans-serif", fixedsize=true, width=1.2];
  	edge [arrowhead=vee, minlen=2];

  	c; d; a; b;
  	
  	a -> b [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>f(state)</td>
  			       </tr>
  			</table>
  		>
  	]

  	c -> d [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>g(state)</td>
  			       </tr>
  			</table>
  		>
  	]
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-arrow-parallel.svg]]

In the context of the game demo, each of the external inputs such as
~LeftClick~, ~RightClick~, ~GameTick~, are stood parallel, as they are
orthogonal actions. This demonstrates the use of the first operation
as a means of append completely new lines of logic to the system.

The second operation will consider arrows ~a -f> b~ and ~b -g> c~,
where one arrow's emission matches the other's trigger. In such cases,
we can sequence the arrows one after the other.

#+begin_src dot :file games-as-graphs-arrow-sequenced.svg :exports results
  digraph G {
  	rankdir=LR;
  	node [shape=circle, fontname="sans-serif", fixedsize=true, width=1.2];
  	edge [arrowhead=vee, minlen=2];

  	a -> b [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>f(state)</td>
  			       </tr>
  			</table>
  		>
  	]

  	b -> c [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>g(state)</td>
  			       </tr>
  			</table>
  		>
  	]
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-arrow-sequenced.svg]]

Turning to the game demo again, sequencing appears in chain reactions
like the one from ~GameTick~ to ~PhysicsTrigger~, and finally to
~PhysicsResult~. The second operation then allows for small, isolated
pieces of logic to combine into long chains of operations.

There is now enough vocabulary to represent linear flows. The last two
operations will then focus on branching control flow.

The third operation handles the creation of branches. Given ~a -f> b~
and ~a -g> c~, the operation branches a single input of ~a~ into both
paths. This branching action is called a /fan-out/.

#+begin_src dot :file games-as-graphs-arrow-fanout.svg :exports results
  digraph G {
  	rankdir=LR;
  	node [shape=circle, fontname="sans-serif", fixedsize=true, width=1.2];
  	edge [arrowhead=vee, minlen=2];

  	a -> b [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>f(state)</td>
  			       </tr>
  			</table>
  		>
  	]

  	a -> c [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>g(state)</td>
  			       </tr>
  			</table>
  		>
  	]
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-arrow-fanout.svg]]

Though represented in individual pieces for clarity in the game graph,
the mouse button events actually unify under an ~Event~, which we fan
out to various handlers like ball spawning and surface creation.

For the final operation, we will undo our fanout by joining
branches. With arrows ~a -f> c~ and ~b -g> c~, since both output a
~c~, we join them at the output so that either one of ~a~ or ~b~ can
trigger a ~c~. The joining action is called a /fan-in/.

#+begin_src dot :file games-as-graphs-arrow-fanin.svg :exports results
  digraph G {
  	rankdir=LR;
  	node [shape=circle, fontname="sans-serif", fixedsize=true, width=1.2];
  	edge [arrowhead=vee, minlen=2];

  	a -> c [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>f(state)</td>
  			       </tr>
  			</table>
  		>
  	]

  	b -> c [
  		labeldistance=4,
  		labelangle=0,
  		headlabel=<
  			<table bgcolor="white" border="0">
  			       <tr>
  					<td>g(state)</td>
  			       </tr>
  			</table>
  		>
  	]
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-arrow-fanin.svg]]

In the game, all operations fan into a single exit event. Similarly,
each one of ~RightClick~, ~RightHold~, and ~RightRelease~ fan into a
~DrawSurf~ event.

With the four operations complete, let's revisit the game one final
time, and carve up the graph into each individual arrow we can find.

#+begin_src dot :file games-as-graphs-fsm-2-indv.svg :exports results
  digraph G {
  	rankdir=TD
  	edge [arrowhead=vee, minlen=2]
  	
  	node [fontname="sans-serif", shape=rectangle, penwidth=0]
  	decidePhysics [label="decidePhysics"]
  	applyPhysics [label="applyPhysics"]
  	updateGame [label="updateGame"]
  	spawnBall [label="spawnBall"]
  	startDraw [label="startDraw"]
  	updateDraw [label="updateDraw"]
  	finaliseDraw [label="finaliseDraw"]
  	spawnSurfOrWait [label="spawnSurfOrWait"]

  	node [shape=point]
  	X; X2; X3; X4;

  	node [shape=circle, penwidth=1.0, fixedSize=true, width=1.2]

  	GameTick -> decidePhysics [arrowhead=none, color=red]
  	decidePhysics -> PhysicsTrigger [color=red]
  	decidePhysics -> X [color=red]

  	PhysicsTrigger2 [label="PhysicsTrigger"]
  	PhysicsTrigger2 -> applyPhysics [arrowhead=none, color=green]
  	applyPhysics -> PhysicsResult [color = green]

  	PhysicsResult2 [label="PhysicsResult"]
  	PhysicsResult2 -> updateGame [arrowhead=none, color=blue]
  	updateGame -> X2 [color=blue]

  	LeftClick -> spawnBall [arrowhead=none, color=orange]
  	spawnBall -> X3 [color=orange]

  	RightClick -> startDraw [arrowhead=none, color=purple]
  	startDraw -> DrawSurf [color=purple]

  	DrawSurf2 [label="DrawSurf"]
  	RightHold -> updateDraw [arrowhead=none, color=cyan]
  	updateDraw -> DrawSurf2 [color=cyan]

  	DrawSurf3 [label="DrawSurf"]
  	RightRelease -> finaliseDraw [arrowhead=none, color=yellow]
  	finaliseDraw -> DrawSurf3 [color=yellow]

  	DrawSurf4 [label="DrawSurf"]
  	DrawSurf4 -> spawnSurfOrWait [arrowhead=none, color=lime]
  	spawnSurfOrWait -> X4 [color=lime]
  }

#+end_src

#+RESULTS:
[[file:games-as-graphs-fsm-2-indv.svg]]

#+begin_src dot :file games-as-graphs-fsm-2-hl.svg :exports results
  digraph G {
  	rankdir=LR;
  	edge [arrowhead=vee, minlen=2];

  	X [shape=point];
  	
  	node [fontname="sans-serif", shape=rectangle, penwidth=0];
  	triggerCond[label="if tasks.empty()"];
  	triggerElse[label="else"];
  	triggerBranch[label="", width=0];

  	node [shape=circle, penwidth=1.0];
  	GameTick -> triggerBranch [arrowhead=none, color=red];
  	triggerBranch -> triggerCond [arrowhead=none, color=red]
  	triggerCond -> PhysicsTrigger [color=red];

  	triggerBranch -> triggerElse [arrowhead=none, color=red];
  	triggerElse -> X [color=red];

  	PhysicsTrigger -> PhysicsResult [color=green];

  	PhysicsResult -> X [color=blue];

  	LeftClick -> X [color=orange];

  	RightClick -> DrawSurf [color=purple];
  	RightHold -> DrawSurf [color=cyan];
  	RightRelease -> DrawSurf [color=yellow];
  	DrawSurf -> X [color=lime];
  }
#+end_src

#+RESULTS:
[[file:games-as-graphs-fsm-2-hl.svg]]

Some operations we can see in use here have already been mentioned,
but with this new visual, we can see things more clearly. For example,
there are three distinct arrows (purple, cyan, yellow) convering on a
point (DrawSurf). We called this a /fan-in/ previously. Similarly, we
see that red, green, blue is a sequence of three controllers. Red
itself naturally contains a branching output, but this is due to its
output being a variant (Either PhysicsTick or Exit), which is decided
based on internal logic.

** Conclusion & What's Next?

Just as ECS is the modularisation of data, treating each arrow on the
graph as a composable piece provides modularisation of event
handlers. However, beside the modular perspective, the two approaches
diverge quickly. While the ECS treats data as first class, our arrow
system treats data as secondary. In fact, currently, all state is
global. This is complete chaos, since accidental mutations can break
the isolation of events. Similarly, while ECS has an answer for large
operations (grouping similar data in tables for fast access), our
event graphs are currently acyclic, meaning feedback loops and bulk
actions can't be formulated. The absence of state isolation and
looping tasks creates a huge barrier for game creation.

To close up these holes in the architecture, the next two posts
explore various concepts. The first post introduces a new concept that
masks values we don't care about to prevent accidental mutation. The
second post introduces a scheduler system that can handle large tasks
like collision and pathfinding asynchronously.

*Note:* The game's implementation can be found on [[https://github.com/Pancakey8/balls/tree/main][Github]] or
 [[https://codeberg.org/Pancakey8/balls/src/branch/main][Codeberg]]. It is written in /Idris/, which is a functional
 language. For readers foreign to functional code, searching
 ~interface Arrow~ in ~src/Component.idr~ brings the type definitions
 of the operations defined in this post, which should provide some
 syntactic visual of how things look behind the scenes.
